service: product-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: default
  stage: shop
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-920c168e
    subnetIds:
      - subnet-31bee657
      - subnet-f1fcd9ae
      - subnet-c5678f89
      - subnet-d2785ef3
      - subnet-35f39f04
      - subnet-c4f9ebca
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action: 'sns:*'
          Resource:
            Ref: createProductTopic
  environment:
    SNS_ARN:
      Ref: createProductTopic

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true


functions:
  getProducts:
    handler: handler.getProducts
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
  addProduct:
    handler: handler.addProduct
    events:
      - http:
          path: products
          method: post
          cors: true
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn: arn:aws:sqs:us-east-1:357231206761:catalogItemsQueue

resources:
  Resources:
    AWSLambdaVPCAccessExecutionRole:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Creating policy for vpc connetion.
        Roles:
          - {"Ref" : "IamRoleLambdaExecution"}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DeleteNetworkInterface
              Resource: "*"
    createProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: PRODUCT_CREATED
    basicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: anaira682190@gmail.com
        Protocol: email
        TopicArn:
          Ref: createProductTopic
    specialSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: anaira682199@gmail.com
        Protocol: email
        TopicArn:
          Ref: createProductTopic
        FilterPolicy:
          title:
            - 'Specialized Diverge Comp E5'
            - 'Giant Contend AR 3'
