service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: default
  stage: shop
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action: 's3:ListBucket'
          Resource:
            - 'arn:aws:s3:::nodejs-aws-import-service-bucket'
        - Effect: 'Allow'
          Action: 's3:*'
          Resource:
            - 'arn:aws:s3:::nodejs-aws-import-service-bucket/*'
        - Effect: 'Allow'
          Action: 'sqs:*'
          Resource:
            - Fn::GetAtt: [ catalogItemsQueue, Arn ]
  environment:
    SQS_URL:
      Ref: catalogItemsQueue

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                name: true
          cors: true
          authorizer:
            name: requestAuthorizer
            identitySource: method.request.header.Authorization
            type: token
            resultTtlInSeconds: 0
            arn: "arn:aws:lambda:us-east-1:357231206761:function:authorization-service-dev-basicAuthorizer"
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: 'nodejs-aws-import-service-bucket'
          event: 's3:ObjectCreated:*'
          rules:
            - prefix: 'uploaded/'
          existing: true

resources:
  Resources:
    catalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
