service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: default
  stage: shop
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action: 's3:ListBucket'
          Resource:
            - 'arn:aws:s3:::nodejs-aws-import-service-bucket'
        - Effect: 'Allow'
          Action: 's3:*'
          Resource:
            - 'arn:aws:s3:::nodejs-aws-import-service-bucket/*'
        - Effect: 'Allow'
          Action: 'sqs:*'
          Resource:
            - Fn::GetAtt: [ SQSQueue, Arn ]
  environment:
    SQS_URL:
      Ref: SQSQueue

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                name: true
          cors: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: 'nodejs-aws-import-service-bucket'
          event: 's3:ObjectCreated:*'
          rules:
            - prefix: 'uploaded/'
          existing: true

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
